### ISSUE TITLE
DPS not calculated correctly in some cases

### ISSUE THREAD

**Issue by Thurion** [Thurion/shield_tester#1]
See https://github.com/Freaky/elite_shield_tester/issues/1 for details about negative DPS.
There is also the possibility of positive DPS and two loadouts having the same survival time. In that case the one that comes first is chosen but better a shield regeneration rate should be preferred.

**Comment by Freaky** [comment]
The case of two different loadouts with different regen but identical survival times seems wildly unlikely - there will be crossover points where the higher hitpoints of one shield matches the higher regen of another, but they'll be knife-edges either side of which there's a more clear winner.

Then it becomes a case of - yes, this shield survives a fraction longer, but that shield recharges quicker outside of battle.  It's less a case of miscalculating stuff and more a case of not giving a clear overview of the result space.

**Comment by Thurion** [comment]
True.
I think it would be best to just show multiple results in that case but then I assume that prismatics and bi-weaves will overlap in most of those cases. And the user can already decide if they want use prismatics or not.
So I won't add a "fix" for positive DPS overlaps. Some of the code is fragmented enough as it is :/
