### ISSUE TITLE
data.json?

### ISSUE THREAD

**Issue by towi** [Thurion/shield_tester#2]
I was able to get it running with the bleeding edge Python inside a docker, but I cant figure out where to get "data.json" from. I tried to export a coriolis and a edsm build, but they lack the "ships" tag. So... how to get a data.json?

**Comment by Thurion** [comment]
Either copy it from the release of https://github.com/Thurion/D2EA_Shield_tester/releases or use https://github.com/Thurion/Shield-Tester-Data

I updated the readme so people don't have to guess.
