### ISSUE TITLE
directory structure

### ISSUE THREAD

**Issue by towi** [Thurion/shield_tester#3]
I would suggest not to put all the files that clearly belong inside a module directory into the directory.
You don't need to follow the disttools but I'd suggets at least:
 * create a subdir shield_tester
 * put all the *.py files of the module in there
 * thus one can put a main file ("towi.py" in my case) in the main dir and use the example that you have in your docs

example `towi.py`:

    #!/usr/bin/env python3
    import shield_tester as st
    def main():
        tester = st.ShieldTester()
    ...

I also suggest using docker (for the py3.8 support). I put my docker calls inside a `Makefile`:

    DOCKER_IMAGE:=python:3.8-slim
    pwd=$(shell pwd)

    run-towi: towi.py
        docker run --rm -i -t -v $(pwd):/root -w /root $(DOCKER_IMAGE) python3 towi.py

**Comment by Thurion** [comment]
The reason it's not in a sub directory is because it is used as git module in https://github.com/Thurion/D2EA_Shield_tester and would end up in a sub directory of a sub directory.
